#!/bin/sh
#
#    10-help-text - print the help text associated with the distro
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>,
#             Brian Murray <brian@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_RELEASE" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_RELEASE=$(lsb_release -sr)
fi

URL="https://help.ubuntu.com/"
if uname -r | grep -qs "\-server"; then
	URL="https://help.ubuntu.com/$DISTRIB_RELEASE/serverguide/C"
fi

printf "\n * Author:         %s\n" "Longgeek <longgeek@thstack.com>"
printf " * Company:        %s\n" "http://www.thstack.com/"
printf " * WebSite:        %s\n" "http://www.livestack.org/"
printf " * Documentation:  %s\n" "$URL"
printf "                   %s\n" "https://www.openstack.org/"
printf '
 m        "                   mmmm    m                  #                                    
 #      mmm    m   m   mmm   #"   " mm#mm   mmm    mmm   #   m          mmm    m mm   mmmm    
 #        #    "m m"  #"  #  "#mmm    #    "   #  #"  "  # m"          #" "#   #"  " #" "#    
 #        #     #m#   #""""      "#   #    m"""#  #      #"#           #   #   #     #   #    
 #mmmmm mm#mm    #    "#mm"  "mmm#"   "mm  "mm"#  "#mm"  #  "m    #    "#m#"   #     "#m"#    
                                                                                      m  #   
                                                                                       ""  '
printf "\n * Use the livestack-status command to check
 * the OpenStack status of the projects!\n"
