#!/bin/bash

## LiveStack
change_vnc () {
    for i in nova.conf nova.conf.spice
    do
        sed -i "s/^novncproxy_base_url.*$/novncproxy_base_url=http:\/\/$IPADDR:6080\/vnc_auto.html/g" /etc/puppet/files/nova/etc/$i
        sed -i "s/^html5proxy_base_url.*$/html5proxy_base_url=http:\/\/$IPADDR:6082\/spice_auto.html/g" /etc/puppet/files/nova/etc/$i

    done
}

if [ "$(facter fqdn)" = "" ]; then
    server_name=$(facter hostname)
else
    server_name=$(facter fqdn)
fi

sed -i "s/server.*$/server=$server_name/g" /etc/puppet/puppet.conf
IPADDR=$(ifconfig eth0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')
if [ "$IPADDR" = "" ]; then
    IPADDR=$(ifconfig br-ex | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')
fi
if [ "$IPADDR" = "" ]; then
    IPADDR='127.0.0.1'
    change_vnc
else
    change_vnc
fi
