#!/bin/bash

update_kvm_type () {
    sed -i "s/^virt_type.*$/virt_type=$virt_type/g" /etc/puppet/files/nova/etc/nova.conf
    sed -i "s/^virt_type.*$/virt_type=$virt_type/g" /etc/puppet/files/nova/etc/nova.conf.neutron
}
kvm-ok > /dev/null 2>&1

if [ "$?" -eq "0" ]; then
    virt_type='kvm'
else
    virt_type='qemu'
fi
[ -e /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -q -N ''
[ -e /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -q -N ''
update_kvm_type
puppet agent --enable
/etc/init.d/puppetmaster start
/etc/init.d/puppet restart
ifconfig eth0 up
/etc/init.d/networking restart
